CREATE DATABASE cvjobfit;
USE cvjobfit;
CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE cvs (
  id INT PRIMARY KEY AUTO_INCREMENT,
  userId INT NOT NULL,
  content TEXT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(id)
);
CREATE TABLE job_offers (
  id INT PRIMARY KEY AUTO_INCREMENT,
  cvId INT,
  text TEXT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (cvId) REFERENCES cvs(id)
);